### ISSUE TITLE
User should be able to send Direct Messages to other Users

### ISSUE THREAD

**Issue by jwhyteBNA** [nss-day-cohort-62/giffy-gram-giforjif#2]
Given the user wants to send messages to another user
When a user selects the Direct Message icon (pen in Navbar)
Then the direct message form should be viewable above the post feed

Given the user wants to send a message to a specific user
When the user selects a recipient
Then the chosen recipient should be saved to transient stage

Given the user wants to send a message
When the user has completed their message and clicks the save button
Then the current message will be saved to a permanent state for the user to view in their messages
And the direct message form should reset to initial state for new message to be created

Given the user decides to cancel a message
When the user clicks the cancel button
Then the direct message form should reset to its initial state for a new message to be created

**Comment by emekaakoma** [comment]
Created a message form with the ability to save and cancel. also added a window.close function to the x button
