### ISSUE TITLE
User should be able to create new post

### ISSUE THREAD

**Issue by Gorthyn** [nss-day-cohort-62/giffy-gram-giforjif#4]
Given the user wants to make a new post
When the user interacts with the feed
Then display button for generation of post form
And form displays upon click

Given the user has clicked the button to display the form
When the user fills the post form and clicks the save button
Then save the current state of the form to permanent state
And display the new post in the feed

Given the user has clicked the button to display the form
When the user fills the post form and clicks the cancel button
Then the post form should reset to its initial state for a new post to be created
And the section should reset back to the display button

Given the user has created a new post
When interacting with the feed
Then increment total number of posts since date of new post in footer

**Comment by jwhyteBNA** [comment]
Dylan built new post form and feed. All worked together on favorites star and trash buttons, and iterating filtered number of posts in footer.
