### ISSUE TITLE
User should be able to filter their feed

### ISSUE THREAD

**Issue by Gorthyn** [nss-day-cohort-62/giffy-gram-giforjif#5]
Given user wants to filter by author
When interacting with the footer
Then display a <select> box to select author by their username
And display posts only from selected author

Given the user wants to see number of posts since "date"
When interacting with the footer
Then display a <select> box to select "year since"
And display only posts made since the date selected

Given the user wants to see number of posts since "date"
When interacting with the footer
Then display the count of posts since chosen date in footer

Given the user wants to only see posts they have favorited
When interacting with the footer
Then display a checkbox that, when clicked, will display only favorited posts

**Comment by jwhyteBNA** [comment]
Jess built out HTML for footer foundations. Ernie did much of the heavy lifting on filtering by user and checking and unchecking favorites, with input from the rest of the group for troubleshooting. Posts sorted by year was a group effort based on other footer filters.
