### ISSUE TITLE
User should be able to navigate the site via the navbar

### ISSUE THREAD

**Issue by erniefabian3rd** [nss-day-cohort-62/giffy-gram-giforjif#6]
Given the user wants to return home
When interacting with the navbar
Then display a clickable logo that refreshes the page

Given the user wants to write a message to a GIFriend (tm)
When interacting with the navbar
Then display a clickable pen icon that opens the message form

Given the user wants to see how many unread messages they have
When interacting with the navbar
Then display a notification icon that alerts user to number of unread messages

Given the user wants to view their received messages
When interacting with the navbar
Then display a clickable notification icon that takes user to page with list of all received messages

Given the user wants to logout from application
When interacting with the navbar
Then display a clickable "Log Out" link that takes user back to login page
And returns application to its original state

**Comment by jwhyteBNA** [comment]
Ernie built out HTML foundations for navBar, and then began assigning event listeners with group help on troubleshooting. Jess built out message notification iteration and logout event listener.
