### ISSUE TITLE
User should be able to interact with specific posts

### ISSUE THREAD

**Issue by emekaakoma** [nss-day-cohort-62/giffy-gram-giforjif#7]
Given a user wants to favorite a post
When a user clicks the star icon
Then the post should be saved to the favorite's database
And linked specifically to the user who favorited it

Given a user wants to remove a favorite from a post
When the user clicks the highlighted star icon
Then the post should be deleted from the favorite's database

Given a user wants to delete a post they have authored
When the user clicks the trash can icon
Then the post should be deleted from the entire database
And no longer display on the page

**Comment by jwhyteBNA** [comment]
Favorite functions, deleting posts, and event listeners were worked on as a group.
